fix crash when `overrideDeviceName` is missing in web
bugfender/BugfenderSDK-Flutter pull request #35
Opened 2024-02-08 18:13 UTC by jgimenez

Description:
* Use the lower-level JsObject API instead of automatically-converted classes to call `Bugfender.init()` because the options object doesn't always have the same keys.

Deployment plan: merge to main
Fallback procedure: revert commit and restore backups if data was lost
Are changes needed in the user's help pages?: no
Are changes needed in the on-premises administrator manual?: no
Are changes needed in the disaster recovery plan?: no

2024-02-08 18:36 UTC, KenjiTakahashi requested changes

2024-02-08 18:36 UTC, KenjiTakahashi commented on lib/flutter_bugfender_web.dart
> +    // We can't use Dart classes with automatic converstion because Dart properties of a class are null when unset, but Bugfender.init() expects undefined.
`converstion`

2024-02-08 18:36 UTC, KenjiTakahashi commented on lib/flutter_bugfender_web.dart
> -      apiURL: apiUri?.toString() ?? 'https://api.bugfender.com',
So we don't care about these default value coercions anymore?

2024-02-08 19:58 UTC, jgimenez commented on lib/flutter_bugfender_web.dart
> -      apiURL: apiUri?.toString() ?? 'https://api.bugfender.com',
The underlying SDK already has defaults. We had them duplicated here as a workaround to avoid sending a variable number of parameters, but because `deviceName` doesn't accept `null`, we can't use this trick anymore.

2024-02-09 14:05 UTC, KenjiTakahashi approved these changes

2024-02-09 15:49 UTC, merged